# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    ignore:
      # ignores minor updates for k8s dependencies so it stays with our cluster version
      - dependency-name: "k8s.io/client-go"
        update-types: ["version-update:semver-minor"]
      # dependabot has conflict issues with the other k8s dependencies, so we update only client-go
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/api"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Europe/Berlin"
    groups:
      golang:
        patterns:
          - "*"
