FROM alpine:latest
ARG TARGETARCH
RUN apk add --no-cache ca-certificates && adduser -D node-drainer
COPY . /test
RUN ls -la /test
COPY dist/node-drainer-linux-${TARGETARCH} /usr/local/bin/node-drainer
USER node-drainer
