[[constraint]]
  name = "github.com/rebuy-de/rebuy-go-sdk"
  version = "1.2.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.8"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.8"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
