# Example service account K8S manifest file, read before applying
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-drainer
---
# ClusterRole is necessary for node-drainer to read node information
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-drainer
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch", "get", "update"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete", "get"]
- apiGroups: [""]
  resources:
  - pods/eviction
  verbs: ["list", "get", "create"]
---
# We must bind the ClusterRole to our new ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-drainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-drainer
subjects:
- kind: ServiceAccount
  name: node-drainer
  namespace: default
