name: Golang

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]
  schedule:
  - cron: '15 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: CI Build

    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Setup tools
      run: |
        go install golang.org/x/lint/golint@latest
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Project
      run: ./buildutil -x linux/amd64 -x linux/arm64 -v

    - name: Generate image tags
      if: ${{ github.event_name != 'release' }}
      shell: bash
      run: |
        if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
          BRANCH="$(echo ${GITHUB_HEAD_REF} | tr '/' '_')"
          echo "##[set-output name=tags;]quay.io/rebuy/node-drainer:${BRANCH},074509403805.dkr.ecr.eu-west-1.amazonaws.com/node-drainer:${BRANCH}"
        elif [ "${GITHUB_EVENT_NAME}" == "release" ]; then
          echo "##[set-output name=tags;]quay.io/rebuy/node-drainer:${GITHUB_REF#refs/tags/},074509403805.dkr.ecr.eu-west-1.amazonaws.com/node-drainer:${GITHUB_REF#refs/tags/}"
        else
          echo "##[set-output name=tags;]quay.io/rebuy/node-drainer:master,074509403805.dkr.ecr.eu-west-1.amazonaws.com/node-drainer:master,\
            quay.io/rebuy/node-drainer:latest,074509403805.dkr.ecr.eu-west-1.amazonaws.com/node-drainer:latest"
        fi
        ls -la
        ls -la dist
      id: generate_tags

    # - name: Set up QEMU
    #   id: qemu
    #   uses: docker/setup-qemu-action@v2
    #   with:
    #     platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    # Only used to prevent rate limits
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: 074509403805.dkr.ecr.eu-west-1.amazonaws.com
        username: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: Dockerfile.multi
        tags: ${{ steps.generate_tags.outputs.tags }}
        platforms: linux/amd64,linux/arm64
